// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'AIzaSy_REPLACE_WITH_FIREBASE_WEB_API_KEY'),
    appId: '1:937328334527:web:ed22e35f4c0726662c180a',
    messagingSenderId: '937328334527',
    projectId: 'tarmim-769e5',
    authDomain: 'tarmim-769e5.firebaseapp.com',
    storageBucket: 'tarmim-769e5.firebasestorage.app',
    measurementId: 'G-1H8PRQSMFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'AIzaSy_REPLACE_WITH_FIREBASE_ANDROID_KEY'),
    appId: '1:937328334527:android:4361fb36203079642c180a',
    messagingSenderId: '937328334527',
    projectId: 'tarmim-769e5',
    storageBucket: 'tarmim-769e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'AIzaSy_REPLACE_WITH_FIREBASE_IOS_KEY'),
    appId: '1:937328334527:ios:607a84fd83a778a42c180a',
    messagingSenderId: '937328334527',
    projectId: 'tarmim-769e5',
    storageBucket: 'tarmim-769e5.firebasestorage.app',
    iosBundleId: 'com.tarmim.fixly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: 'AIzaSy_REPLACE_WITH_FIREBASE_WINDOWS_KEY'),
    appId: '1:937328334527:web:ac572e09938863232c180a',
    messagingSenderId: '937328334527',
    projectId: 'tarmim-769e5',
    authDomain: 'tarmim-769e5.firebaseapp.com',
    storageBucket: 'tarmim-769e5.firebasestorage.app',
    measurementId: 'G-R22109FSN9',
  );
}
